### ISSUE TITLE
Error while executing examples

### ISSUE THREAD

**Issue by wolmi** [bobsta63/xmws-php-client#2]
Hi, I'm trying to work with examples provided but it is imposible:

Warning: Missing argument 1 for xmwsclient::__construct(),
Warning: Missing argument 2 for xmwsclient::__construct(),

Notice: Undefined variable: key
Notice: Undefined variable: wsurl

Fatal error: Call to undefined method xmwsclient::InitRequest()

Are any explanation to the diferences between class and examples?

**Comment by xabixab** [comment]
I have the same error.

**Comment by bobsta63** [comment]
Hi Guys,

I'll update the examples but basically the problem is that you need to pass the ZPanel server URL, Server key and auth credentials in the class constructor now instead of the InitRequest() method!

I'll update the code examples shortly but I would suggest you guys check out my new Sentora/ZPanel API here: https://github.com/bobsta63/senitor

**Comment by xabixab** [comment]
Hi,
Thanks a lot,  I will use senitor.

**Comment by bobsta63** [comment]
You're welcome - Happy Christmas!
